env:
    # Cirrus Specific Vars (Do *NOT* Change)
    CIRRUS_SHELL: bash

task:
  name: "Recovery Build"
  timeout_in: 120m
  container:
      image: ghcr.io/sushrut1101/docker:arch
      cpu: 8
      memory: 20G

  Checks_script:
      - curl -sL https://github.com/EvilAnsh/Scripts/raw/PBRP/AOSP%20Scripts/twrp-build.sh | bash
